### ISSUE TITLE
Drinkable water

### ISSUE THREAD

**Issue by Josharias** [Terasology/JoshariasSurvival#13]
I want to be able to get water from something other than food so that it is easier to manage that part of survival.
- possibly to boil sea-water?
- some sort of crude cup?

**Comment by Josharias** [comment]
Note: Need to modify the Hunger module to add an event so that we can use the fluid containers to contain liquids and empty the container upon drinking instead of also removing the cup itself.

**Comment by Cervator** [comment]
I think this one might be ready to close, @Josharias ! :D

(reference for others: https://www.youtube.com/watch?v=tTVu4CE5MHc)

On a semi-related note would it make sense to submit a simple feature request here to get double seeds if you break a berry bush while holding a crude tool of some sort? Or if you whack at / `e` click a bush with a sharp tool equipped you get a sapling instead of seeds (but still decrease the maturity stage by 1)

**Comment by Cervator** [comment]
Closing this as done long ago
