### ISSUE TITLE
Berry harvesting seems a bit non-intuitive

### ISSUE THREAD

**Issue by bbarker** [Terasology/JoshariasSurvival#21]
I think the user would benefit from knowing that they need to eat directly from a blueberry plant, rather than picking up the berries (this is especially true, I think, if coming from Minecraft). I'm not sure how to best address such a hint (e.g., tutorial/help or tooltip).

**Comment by aaron-harris** [comment]
Well, the Joshaberry bushes haven't been updated yet to incorporate @jellysnake's recent changes to `SimpleFarming`.  I don't know what the state of things was prior to those changes, but the behavior you describe seems pretty weird to me; I suspect that the intention was that right-clicking on the bush should produce berries, as you would expect, but the behavior is/was a little buggy, and hopeful will be improved once Josharias gets updated to the new mechanics.

**Comment by Cervator** [comment]
So berry eating (and sometimes drinking things) have been one of the hot spots for recurring bugs / quirks. I'm not quite sure it is stable yet.

I've heard the confusion bit where somebody is attempting to break a bush block or right click it to get produce, when it is `e` clicking that tends to get berries that can then be eaten out of the hot bar. I figure that's in part from `e` clicking being a Terasology thing that isn't an option in MC. And in part because half the time, well, some step wasn't actually working ... :-)

Reminds me of a few times over the years when default behavior from mouse actions have been discussed. Are we open to changing the expected behavior from the right mouse button, can we write more useful conventions for how to do typical actions, and so on.

**Comment by Cervator** [comment]
Started replying on another issue, but that comment got bigger than intended and some of it is probably more relevant to the discussion here. So linking to the comment here: https://github.com/Terasology/JoshariasSurvival/issues/22#issuecomment-344361846

**Comment by aaron-harris** [comment]
I like the radial menu idea quite a bit (in the comment @Cervator links to), especially since it allows for open-ended extension pretty easily.

I'm not sure how I feel about the default action being eating, or rather that it is that easy to eat things by mistake.  Maybe that's just too much familiarity with Minecraft, where you have to hold down the right mouse button to eat, and you get feedback that that's what's happening.

My own personal preference, which I do not expect to be universal, would be:

* Left click: Break target block.
* `e` key: Activate target block.
* Right click: Plant berry, if possible.
* Hold right click: Eat berry.
* Hold middle click: Open radial menu.

In order to support that setup, I would allow each item to specify both a primary action and a secondary action, and then create actions/commands/things-bindable-to-keys for:

* Break target block (my left click, your left click)
* Activate target block (my `e`, your `e`)
* Primary function (my right click)
* Secondary function (my hold right click)
* Context-sensitive/DWIM function (try primary, then secondary) (your right click)
* Radial menu (my hold middle click, your hold right click)

If we allow all of those to be bound freely (and let hold right click be bound independently of ordinary right click), then we can support both configurations, and others.

**Comment by Cervator** [comment]
I've started wondering about taking the system further, to where you could flow into a radial menu on various keys/buttons, not just a single given one for *the* radial menu. It would depend heavily on what's equipped/held.

* Left click: usually apply damage. I'm not sure of any examples that would overload left click as you may well want to have the "hold left" for continuing to apply damage (but then, really, that holding action could theoretically be rebound itself)
* `e` key: builds its options based on the target block. A chest simply opens. A super duper deluxe chest with a dozen weird ways to interact with it would roll into a radial menu on holding `e` while a single click would target the most natural action within the context. 
* Right click: same thing based on the held item rather than target item

To expand on the super fancy chest example: you'd have a `chest.prefab` like now, but any component in it could contribute an action. At present the `InteractionTargetComponent` allows the user to interact 
with the chest (using a specific screen via `InteractionScreenComponent`) which leads to the inventory associated with the chest using the `InventoryComponent`. You could have some `FireworksTriggerComponent` added as well, making an action available to launch fireworks from the chest instead of opening it. Probably in this case the inventory interaction should be default over launching fireworks, somehow. It would then appear in a radial menu automatically if the user triggers the radial menu, while a normal single `e` click would open the chest's inventory like normal.

I'm reluctant to recruit the middle mouse button into anything critical, as I see it rarely used. Users can always rebind if desired, yeah, you could even split apart the default action key for `x` and also have a trigger radial for `x` - that way I do suppose both our ideas could work at the same time :-)

I guess what it comes down to is defining the top level actions, then applying some sensible UX to it. For instance in the case of eating something you could have it feel more natural by instead adding a duration and the right click would start it (and begin an animation), but then you could click again to cancel. Considering our entity system focused design I'd like to find a way to dynamically determine a default and let any added `-Component` supply options, rather than rely on explicit primary and secondary actions defined on items.

Maybe we could call these "action trails"  - a basic system that would include two bindings (single press and holding) and could have actions registered to them, with weights or contexts to determine a default. So `e` and right clicking would be two such registered systems in the base game. If authors want to add one they could do so, for instance an in-game emote system where you could pick a default emote but hold the binding to trigger a radial with all available (registered to that system) emotes.

Potential drawback: what if an item *wants* to use holding the mouse button for an action (like a bow). Either we'd have to encourage anything requiring a holding action to use the left mouse button (if we make that a convention), a different binding (that could be fair - imagine an off-hand action trail for bows or shields), or components would be able to claim exclusive control over an action trail.

**Comment by aaron-harris** [comment]
That sounds promising, but I need some time to digest it before I can provide a fully thought-out response.  In the meantime, I had another thought: we (or an individual user) might want to also use modifier keys (like Minecraft's sneak-right-click).  We're rapidly approaching "button saturation", but we should probably consider it.

**Comment by Cervator** [comment]
Yeah I'm still digesting myself. Have another write-up with a silly amount of flexibility, but it is probably too complex/unwieldy.

Comes down to whether a nicer system can be written up that supports optional depth while offering simplicity up front that can be made to feel very natural. And whether doing so makes enough additional users happy to be worth it (one big angle there: accessibility for any users with special needs)

Throwing modifier keys into my write-up, thanks, actually release needed that ...  :D

**Comment by jdrueckert** [comment]
@Cervator This issue seems like it started out as a (potentially) valid issue (read: problem) that was soon buried by dreamland :sweat_smile: Afaik the original issue as it was does not persist anymore, so should we maybe close this?

**Comment by bbarker** [comment]
Fine by me!
